spin_manifest_version = 2

[application]
name = "hello-spinkube"
version = "0.1.0"
authors = ["Kate Goldenring <kate.goldenring@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "hello-spinkube"

[component.hello-spinkube]
source = "main.wasm"
allowed_outbound_hosts = []
[component.hello-spinkube.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
