apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohash-containerized
  labels:
    app: gohash-containerized
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gohash-containerized
  template:
    metadata:
      labels:
        app: gohash-containerized
    spec:
      containers:
      - name: gohash-containerized
        image: ghcr.io/kate-goldenring/gohash-container:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 128Mi
        #   requests:
        #     cpu: 100m
        #     memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gohash-containerized
spec:
  selector:
    app: gohash-containerized
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000